name: "Build dotnet web app"

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - run: curl -SL --output vs_buildtools.exe https://aka.ms/vs/17/release/vs_buildtools.exe && ./vs_buildtools.exe --quiet --wait --norestart --nocache --add Microsoft.VisualStudio.Workload.WebBuildTools
    - run: dir "C:\Program Files\"
    - run: dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\"
    - run: dir "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\"

