name: "Build dotnet web app"

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - run: dir "C:\Program Files\dotnet\sdk"
    - run: dotnet --version && dotnet --list-sdks && dotnet --list-runtimes && dotnet --info
