name: "Build dotnet web app"

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - run: dotnet --info && ls -lah /usr/share/dotnet
